name: Run Python unit tests

#env:

on:
  pull_request:
    branches:
      - "main"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Build Poetry Lock file
    #   uses: snok/install-poetry@v1
    # - run: poetry lock

    - name: Install dependencies via Poetry
      uses: snok/install-poetry@v1
    - run: poetry install

    - name: Run linting
      run: poetry run ruff check .

    - name: Run Tests and Coverage
      run: poetry run coverage run -m --source=src pytest tests/

    - name: Build Coverage XML
      run: poetry run coverage xml

    - name: Display Coverage
      uses: 5monkeys/cobertura-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 80
        fail_below_threshold: false
